### ISSUE TITLE
Synced Column Not Showing Correct Status

### ISSUE THREAD

**Issue by meburnsrv** [idahogurl/TogglToJiraSync#17]
The Synced column of the time entries table is not displaying `Yes` anymore for entries that have been synced.
<img width="750" alt="Screen Shot 2021-02-09 at 4 13 51 PM" src="https://user-images.githubusercontent.com/21184644/107441230-2298c800-6af2-11eb-8473-a606c9a9abff.png">

All of the entries displayed above have already been synced. For a day or so checking the checkbox made the `Yes` show up, but that is no longer the case
<img width="750" alt="Screen Shot 2021-02-09 at 4 14 08 PM" src="https://user-images.githubusercontent.com/21184644/107441299-3d6b3c80-6af2-11eb-88e3-8af888c3296d.png">

So now I'm not sure which entries to sync so they don't get sent twice

**Comment by idahogurl** [comment]
@meburnsrv The issue appears to be related to Jira's API being down/broken. I'm thinking of popping up an error saying they did not sync.

**Comment by idahogurl** [comment]
We found out she was on an older version. Creating a ticket to inform user to upgrade. Not sure of the LOE to have it download, install and restart. Putting the download url based on OS should be good enough.

**Comment by idahogurl** [comment]
We found out she was on an older version. Created a ticket #19 to add a notification to inform user to upgrade. Not sure of the LOE to have it download, install and restart. Putting the download url based on OS should be good enough. I should start versioning my API so it's not required to upgrade right then. I will have to inform them it is a breaking change this time so I can add the version number. Need to do a change log too.
